/* The comparison matrix, as data. Each row is [label, note, basic, growth,
   scale, command, sovereign]; a group header is ["grp", title].
   "y" renders a tick, "n" a dash, anything else renders as text. */
export const MATRIX = [
  ["Price per user / month", "minimum 5 users on every plan", "£29", "£69", "£119", "£169", "Custom"],
  ["grp", "Core platform"],
  ["CRM — contacts, cases & pipeline", null, "y", "y", "y", "y", "y"],
  ["Live dashboards & reporting", null, "y", "y", "y", "y", "y"],
  ["Task hoppers & agent workbench", null, "y", "y", "y", "y", "y"],
  ["Documents & letter templates", null, "y", "y", "y", "y", "y"],
  ["E-signatures", "send, sign & auto-file to the record", "n", "y", "y", "y", "y"],
  ["Signature sends per month", null, "n", "250", "1,000", "Unlimited*", "Custom"],
  ["Forms & surveys", null, "y", "y", "y", "y", "y"],
  ["Websites, funnels & landing pages", null, "n", "y", "y", "y", "y"],
  ["grp", "Channels"],
  ["Email sending", null, "y", "y", "y", "y", "y"],
  ["Two-way SMS", "inbound replies free on every plan", "y", "y", "y", "y", "y"],
  ["Social DMs — Facebook & Instagram", null, "n", "y", "y", "y", "y"],
  ["Website chat widget", null, "n", "y", "y", "y", "y"],
  ["WhatsApp Business", null, "n", "y", "y", "y", "y"],
  ["VoIP dialler connection", null, "n", "y", "y", "y", "y"],
  ["Call tracking", null, "n", "y", "y", "y", "y"],
  ["Missed-call text-back", null, "n", "y", "y", "y", "y"],
  ["Team communication", null, "n", "y", "y", "y", "y"],
  ["grp", "AI workforce"],
  ["Conversation AI", "bot on WhatsApp, SMS & website chat, 24/7", "n", "n", "y", "y", "y"],
  ["AI automated workflows", null, "n", "n", "y", "y", "y"],
  ["AI email management", null, "n", "n", "y", "y", "y"],
  ["AI call scoring — 100% of calls", null, "n", "n", "y", "y", "y"],
  ["AI assistant for every agent", null, "n", "n", "n", "y", "y"],
  ["Voice AI", "answers & makes calls, day and night", "n", "n", "n", "y", "y"],
  ["AI training & live coaching", null, "n", "n", "n", "y", "y"],
  ["grp", "Marketing & revenue"],
  ["Email marketing campaigns", null, "n", "y", "y", "y", "y"],
  ["Payment links & plan tracking", null, "n", "y", "y", "y", "y"],
  ["Lead distribution (round-robin)", null, "n", "y", "y", "y", "y"],
  ["Meta / Google / TikTok attribution", null, "n", "n", "y", "y", "y"],
  ["Prospecting tool", null, "n", "n", "y", "y", "y"],
  ["Ad Manager", "run Google, Facebook & Instagram ads", "n", "n", "n", "y", "y"],
  ["Full marketing suite & funnels", null, "n", "n", "n", "y", "y"],
  ["grp", "Team management"],
  ["Team monitoring & leaderboards", null, "n", "n", "y", "y", "y"],
  ["Client update portal", "live status, uploads, e-sign & payments", "n", "n", "y", "y", "y"],
  ["grp", "Power & platform"],
  ["Branded company app", "iOS & Android, built by our engineers", "n", "Add-on", "Add-on", "y", "y"],
  ["Partner & introducer portal", null, "n", "Add-on", "y", "y", "y"],
  ["Branded company app", "engineer-built on your CRM", "n", "Via build hours", "Via build hours", "y", "y"],
  ["Online & partner portals", null, "n", "Add-on", "Add-on", "y", "y"],
  ["Client document & ID uploads", null, "n", "y", "y", "y", "y"],
  ["OCR document reading", "data extracted from uploads automatically", "n", "n", "y", "y", "y"],
  ["Open Banking suite", "affordability, validation & banking data", "n", "n", "n", "y", "y"],
  ["Open API & custom modules", null, "n", "n", "n", "y", "y"],
  ["Managed cloud hosting", "secure UK cloud, backups included", "y", "y", "y", "y", "Your cloud"],
  ["Dedicated cloud server", null, "Add-on", "Add-on", "Add-on", "y", "y"],
  ["VoIP phone system", "pay-as-you-go numbers & minutes", "Add-on", "y", "y", "y", "y"],
  ["Self-hosted in your own cloud", null, "n", "n", "n", "n", "y"],
  ["Uptime SLA & named engineers", null, "n", "n", "n", "n", "y"],
  ["grp", "Allowances"],
  ["Contacts", null, "25,000", "75,000", "250,000", "Unlimited*", "Custom"],
  ["Emails per month", null, "15,000", "50,000", "150,000", "500,000", "Custom"],
  ["Leads per bulk action", null, "2,000", "10,000", "25,000", "Unlimited*", "Custom"],
  ["Brands", null, "1", "3", "Unlimited", "Unlimited", "Custom"],
  ["grp", "Bespoke build & support"],
  ["Customisation", "can the CRM be changed for you?", "Fixed — as supplied", "Tailored", "Bespoke", "Fully bespoke", "Unlimited scope"],
  ["Bespoke build hours included", null, "n", "10 hrs", "30 hrs", "60 hrs + 5/mo", "Scoped"],
  ["Automations built for you", null, "n", "Setup only", "y", "y", "y"],
  ["IT support", null, "Email, business hrs", "Business hrs", "Priority, 8am–8pm", "**24/7", "**24/7 + SLA"],
  ["Dedicated success manager", null, "n", "n", "n", "y", "y"],
  ["Data migration handled", null, "y", "y", "y", "y", "y"],
  ["14-day free trial", null, "y", "y", "y", "y", "y"],
];
