/* Plan data lives here so the cards, the comparison matrix and the JSON-LD
   offers all read from one place — three renderings of the same prices cannot
   drift apart the way three hand-maintained copies would. */

export const PLANS = [
  {
    id: "Basic",
    name: "Basic",
    icon: "home",
    for: "Off-the-shelf CRM. Use it as it comes — no changes, no build.",
    monthly: 29,
    annual: 24,
    billM: "MIN 5 USERS · FROM £145/MO",
    billA: "MIN 5 USERS · FROM £1,440/YR",
    users: "Minimum 5 users",
    cta: "ghost",
    ctaLabel: "Start free trial",
    features: [
      ["hd", "Core"],
      ["li", <>Full CRM — contacts, cases &amp; pipeline</>],
      ["li", <>Live dashboard &amp; reporting</>],
      ["li", <>Task hoppers &amp; reminders</>],
      ["li", <>Forms &amp; surveys — capture leads into the CRM</>],
      ["hd", "Channels"],
      ["li", "Email sending (deliverability built in)"],
      ["li", "Two-way SMS, logged to the record"],
      ["hd", "Included"],
      ["li", <>Document &amp; letter templates</>],
      ["li", "Data import handled for you"],
      ["li", "Fixed setup — standard workflows only"],
      ["li", "Email support (business hours)"],
      ["li", <>2 hours training &amp; advice</>],
    ],
    allowances: [["Contacts", "25,000"], ["Emails / month", "15,000"], ["Per bulk action", "2,000"], ["Brands", "1"]],
  },
  {
    id: "Growth",
    name: "Growth",
    icon: "chart",
    for: "Tailored to you. We shape the CRM around your process.",
    monthly: 69,
    annual: 58,
    billM: "MIN 5 USERS · FROM £345/MO",
    billA: "MIN 5 USERS · FROM £3,480/YR",
    users: "Minimum 5 users",
    cta: "ghost",
    ctaLabel: "Start free trial",
    features: [
      ["hd", "Everything in Basic, plus"],
      ["hd", "Channels"],
      ["li", "WhatsApp Business, two-way"],
      ["li", <>VoIP dialler connection &amp; call logging</>],
      ["li", <>Call tracking &amp; missed-call text-back</>],
      ["li", <>Chat widget + social DMs (Facebook &amp; Instagram)</>],
      ["li", "Team communication built in"],
      ["hd", "Revenue"],
      ["li", "Email marketing campaigns"],
      ["li", <>Websites, funnels &amp; landing pages</>],
      ["li", <><b>E-sign</b> — send, sign &amp; auto-file to the record (250 sends/mo)</>],
      ["li", <>Client document &amp; ID uploads — secure links, filed to the case</>],
      ["li", <>Payment links &amp; plan tracking</>],
      ["li", "Smart lead distribution (round-robin)"],
      ["hd", <>Bespoke &amp; support</>],
      ["li", <><b>10 engineer build hours</b> — your statuses, workflows &amp; documents, built for you</>],
      ["li", "IT support, business hours"],
    ],
    allowances: [["Contacts", "75,000"], ["Emails / month", "50,000"], ["Per bulk action", "10,000"], ["Brands", "3"]],
  },
  {
    id: "Scale",
    name: "Scale",
    icon: "shield",
    popular: true,
    for: "Bespoke CRM with your automations built for you — and the AI workforce on.",
    monthly: 119,
    annual: 99,
    billM: "MIN 5 USERS · FROM £595/MO",
    billA: "MIN 5 USERS · FROM £5,940/YR",
    users: "Minimum 5 users · volume rates at 25+",
    cta: "primary",
    ctaLabel: "Start free trial",
    features: [
      ["hd", "Everything in Growth, plus"],
      ["hd", "AI workforce"],
      ["li", <>Conversation AI — bot handles WhatsApp, SMS &amp; your website chat widget, 24/7</>],
      ["li", "AI automated workflows (Automation Studio)"],
      ["li", <>AI email management &amp; triage</>],
      ["li", "100% AI call scoring — every call"],
      ["hd", <>Team &amp; growth</>],
      ["li", <>Team monitoring &amp; live leaderboards</>],
      ["li", <>Client update portal — live case status, uploads, e-sign &amp; payments</>],
      ["li", <>Meta, Google &amp; TikTok ad attribution</>],
      ["li", <>Prospecting tool — find &amp; qualify new leads</>],
      ["li", <>OCR document reading — uploads read &amp; data extracted automatically</>],
      ["li", <><b>E-sign</b> — 1,000 sends/mo, templates auto-filled from record data</>],
      ["hd", <>Bespoke &amp; support</>],
      ["li", <>
        <b>30 engineer build hours</b> — we design &amp; build your AI automations for you
        <small style={{ display: "block", color: "var(--glow)", fontSize: "10.5px", marginTop: 2 }}>
          £3,600+ of build value, included
        </small>
      </>],
      ["li", "Priority IT support, extended hours (8am–8pm)"],
    ],
    allowances: [["Contacts", "250,000"], ["Emails / month", "150,000"], ["Per bulk action", "25,000"], ["Brands", "Unlimited"]],
  },
  {
    id: "Command",
    name: "Command",
    icon: "cog",
    for: "Fully bespoke build, ongoing development, and 24/7 support.",
    monthly: 169,
    annual: 141,
    billM: "MIN 5 USERS · FROM £845/MO",
    billA: "MIN 5 USERS · FROM £8,460/YR",
    users: "Minimum 5 users · volume rates at 25+",
    cta: "ghost",
    ctaLabel: "Start free trial",
    features: [
      ["hd", "Everything in Scale, plus"],
      ["hd", "AI everywhere"],
      ["li", <><b>Voice AI</b> — answers &amp; makes calls, day and night</>],
      ["li", "AI assistant for every agent"],
      ["li", <>AI training &amp; live agent coaching</>],
      ["hd", "Power features"],
      ["li", <>Full marketing suite &amp; funnels</>],
      ["li", <>Ad Manager — run Google, Facebook &amp; Instagram ads from the CRM</>],
      ["li", <><b>E-sign unlimited*</b> — bulk send &amp; signing workflows</>],
      ["li", <><b>Branded company app</b> (iOS &amp; Android) — built &amp; published for you</>],
      ["li", "Branded company app — engineer-built on your CRM"],
      ["li", "Dedicated cloud server included"],
      ["li", <><b>Open Banking suite</b> — credit-acceptance &amp; affordability checks, client validation, banking data obtained on behalf of clients</>],
      ["li", <>Open API &amp; custom modules</>],
      ["hd", <>Bespoke &amp; support</>],
      ["li", <>
        <b>60 engineer build hours</b> + 5 dev hours every month
        <small style={{ display: "block", color: "var(--glow)", fontSize: "10.5px", marginTop: 2 }}>
          £7,200+ of build value, included
        </small>
      </>],
      ["li", "Dedicated success manager"],
      ["li", <><b>24/7 support</b> — phone, chat &amp; email, day or night</>],
    ],
    allowances: [["Contacts", "Unlimited*"], ["Emails / month", "500,000"], ["Per bulk action", "Unlimited*"], ["Brands", "Unlimited"]],
  },
  {
    id: "Sovereign",
    name: "Sovereign",
    icon: "lock",
    for: "Self-hosted in your own cloud. Total data ownership.",
    custom: "Let's talk",
    billM: "TAILORED TO YOUR OPERATION",
    billA: "TAILORED TO YOUR OPERATION",
    users: <>Volume &amp; enterprise terms</>,
    cta: "ghost",
    ctaLabel: "Talk to us",
    features: [
      ["hd", "Everything in Command, plus"],
      ["li", "Deployed in a cloud account you control"],
      ["li", "Your data never leaves your estate"],
      ["li", <>Security &amp; compliance review welcomed</>],
      ["li", "Full migration handled end-to-end"],
      ["li", "Unlimited bespoke build — scoped to you"],
      ["li", "Custom development retainer"],
      ["li", <><b>24/7 support</b> with uptime SLA &amp; named engineers</>],
      ["li", "Founding-client terms available"],
    ],
  },
];
